baseURL = 'https://ydzhou.github.io'
languageCode = 'en-us'
hasCJKLanguage = true
googleAnalytics = 'G-NGR0WHS7KP'
defaultContentLanguage = 'en'

[params]
mainSections = ['tech']
paginationSize = 5

[languages]
[languages.en]
languageName = '🇺🇸'
title = 'nothingowned'
weight = 1
